### ISSUE TITLE
Webtool results link leads to "Page not found" 

### ISSUE THREAD

**Issue by bkille** [the-mitchell-lab/rodeo2#8]
Email from user:

I am a student trying to use RODEO 2 for my master's
thesis and have the following problem, for which I thought you might be
able to help me:

If I try to use the web application, the link in the email of the job
always runs into "Page not found".
I have used several different protein accession numers/ text documents
and email adresses /browsers. I also varied the settings to test if it
might have had something to do with them.
Here is an example link, the website sent me:
http://rodeo.scs.illinois.edu/2/xxxxxxxxx-xxxxxxxx@xxx.edu
Because I did not get the web application to work, I tried to download
Rodeo. I think I installed all the requiered other programs ( I used the
Ubuntu for Windows application) but nevertheless I get the following error:

```
   File "rodeo_main.py", line 7
     <!DOCTYPE html>
     ^
SyntaxError: invalid syntax
```

Sadly, I am not able to fix these problems, even though I tried to.
I have no clue, what might be the problem, so I thought I might as well
send you an email.

Thank you very much in advance for your answer!

**Comment by bkille** [comment]
For the issue w/ the webtool, I believe our web developer put in relatively strict criteria for the email addresses RODEO accepts. I've just modified the criteria and your link should now work just fine. Let me know if otherwise.

Wrt downloding the code, it looks like you have downloaded the html page of the code. Did you use `git clone`? 

Best,

-Bryce

**Comment by FriederikeBiermann** [comment]
Thank you very much!
I used git clone, but still have the same issue.
Best 
Friederike

**Comment by bkille** [comment]
Hmm, interesting, can you show me the exact command used to run rodeo as well as the terminal output?

-B

**Comment by FriederikeBiermann** [comment]
the command I used was
`python3 rodeo_main.py BAL72546 `
-> I just used the example given in the Git Instructions and just modified `python` to `python3`
 
the exact output was: 

```
File "rodeo_main.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by bkille** [comment]
Yup looks right to me. Can you show me the first ~20 lines of your `rodeo_main.py` file? 

`head rodeo_main.py -n 20` should do the trick

**Comment by FriederikeBiermann** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
the first few lines are empty

**Comment by bkille** [comment]
Well that certainly isn't right. Can you show me the command you used to clone the repository? The file should look like [this](https://github.com/the-mitchell-lab/rodeo2/blob/master/rodeo_main.py)

**Comment by FriederikeBiermann** [comment]
`clone git https://github.com/the-mitchell-lab/rodeo2.git`
I am really unexperienced with github, so I did not really knew what to do
Thank you so much for your help!

**Comment by bkille** [comment]
No problem, happy to help!

The first two commands should be swapped 

```
git clone https://github.com/the-mitchell-lab/rodeo2.git
```

**Comment by FriederikeBiermann** [comment]
Oh, I realized that's exactly what I did :)
I just messed up the message

**Comment by bkille** [comment]
Happens to all of us, glad we could figure it out! Let me know if you have any other questions.

**Comment by FriederikeBiermann** [comment]
Now that I got it to work in general, another problem occurred ;(

```
python3 rodeo_main.py BAL72546
Traceback (most recent call last):
  File "rodeo_main.py", line 407, in <module>
    __main__()
  File "rodeo_main.py", line 62, in __main__
    from record_processing import fill_request_queue, ErrorReport
  File "/home/friederike/rodeo2/record_processing.py", line 32, in <module>
    from entrez_utils import get_gb_handles, get_record_from_gb_handle
  File "/home/friederike/rodeo2/entrez_utils.py", line 37, in <module>
    from Bio.Alphabet import generic_dna
  File "/home/friederike/.local/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

I think the problem is that I use a version of Biopython that is too new- do you know a workaround?

Best,
Friederike

**Comment by bkille** [comment]
Oooo interesting. Yup looks like `Alphabet` was removed in 1.78. For now you can either rewind your Biopython package to 1.77 or wait for me to push the update and then clone again.
